:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Com.RedHat
dotnet build src\Com.RedHat
echo Now, run the following to start the project: dotnet run -p src\Com.RedHat\Com.RedHat.csproj --launch-profile web.
echo.
