/*
 * Todo
 *
 * My Todo list API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: deven.phillips@redhat.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Com.RedHat.Attributes;
using Com.RedHat.Models;

namespace Com.RedHat.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class UserApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Return the current user profile</remarks>
        /// <response code="200">The user profile information</response>
        [HttpGet]
        [Route("/api/v1/user")]
        [ValidateModelState]
        [SwaggerOperation("GetUserProfile")]
        [SwaggerResponse(statusCode: 200, type: typeof(User), description: "The user profile information")]
        public virtual IActionResult GetUserProfile()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(User));
            string exampleJson = null;
            exampleJson = "{\n  \"name\" : \"name\",\n  \"preferred_username\" : \"preferred_username\",\n  \"given_name\" : \"given_name\",\n  \"family_name\" : \"family_name\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<User>(exampleJson)
            : default(User);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
